#
# HopperFilter by Trophonix
#

filterFlippedUp:
  - "<dark_aqua>Filter is now</dark_aqua> <green>inclusive</green>"
  - "<gray><italic>Filter will allow through the displayed item.</italic></gray>"
filterFlippedDown:
  - "<dark_aqua>Filter is now</dark_aqua> <red>exclusive</red>"
  - "<gray><italic>Filter will allow through all other items.</italic></gray>"
