name: "HopperFilter"
version: "${project.version}"
api-version: "1.13"
author: trophonix
main: com.trophonix.hopperfilter.HopperFilterPlugin
commands:
  hopperfilter:
    description: "Reload config"
    usage: "/hopperfilter rl"
    permission: "hopperfilter.admin"
permissions:
  hopperfilter.rotate:
    description: "Gives player access to rotate a filter"